spring:
  jpa:
    
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        show_sql: true
  h2:
    console: 
      enabled: true
  
  datasource:
    url: jdbc:h2:file:./selecao-seplag;DB_CLOSE_ON_EXIT=FALSE;
      
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

server:
  servlet:
    context-path: /api/
    
         